[package]
name = "pico-admin"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
handlebars = { version = "6.3.2", features = ["dir_source"] }
serde = "1.0.228"
tokio = { version = "1.47.1", features = ["full"] }
tower = "0.5.2"
